export const SIDEBAR_ITEMS = {
  DEAFULT: "default",
  ECOMMERCE: "eCommerce",
  PRODUCTS: "products",
  ONLINE_COURSES: "onlineCourses",
};

export const SIDEBAR_COMPONENTS = {
  DASHBOARD: "dashboard",
  PAGES: "pages",
  ACTIVITY: "activity",
};

export const RECENT_TABS = {
  FAVOURITES: "favourites",
  RECENTLY: "recently",
};

export const THEMES = {
  LIGHT: "light",
  DARK: "dark",
};

export const dashboardItems = [
  {
    href: "/dashboard/default",
    name: "default",
    label: "Default",
    hasSubRoutes: false,
    icon: "dashboard",
    subRoutes: [],
  },
  {
    href: "/dashboard/ecommerce",
    name: "eCommerce",
    label: "eCommerce",
    icon: "eCommerce",
    hasSubRoutes: true,
    subRoutes: [
      {
        href: "/dashboard/ecommerce",
        name: "example1",
        label: "Example1",
        icon: "eCommerce",
      },
      {
        href: "/dashboard/ecommerce",
        name: "example2",
        label: "Example2",
        icon: "eCommerce",
      },
    ],
  },
  {
    href: "/dashboard/projects",
    name: "projects",
    label: "Projects",
    icon: "projects",
    hasSubRoutes: true,
    subRoutes: [
      {
        href: "/dashboard/projects",
        name: "example1",
        label: "Example1",
        icon: "projects",
      },
      {
        href: "/dashboard/projects",
        name: "example2",
        label: "Example2",
        icon: "projects",
      },
    ],
  },
  {
    href: "/dashboard/online-courses",
    name: "online-courses",
    label: "Online Courses",
    icon: "onlineCourses",
    hasSubRoutes: true,
    subRoutes: [
      {
        href: "/dashboard/online-courses",
        name: "example1",
        label: "Example1",
        icon: "onlineCourses",
      },
      {
        href: "/dashboard/online-courses",
        name: "example2",
        label: "Example2",
        icon: "onlineCourses",
      },
    ],
  },
];

export const pagesItems = [
  {
    href: "/pages/user-profile",
    name: "user-profile",
    label: "User Profile",
    icon: "userProfile",
    hasSubRoutes: true,
    subRoutes: [
      { href: "/pages/user-profile", name: "overview", label: "Overview", icon: "userProfile" },
      { href: "/pages/user-profile", name: "projects", label: "Projects", icon: "userProfile" },
      {
        href: "/pages/user-profile",
        name: "campaigns",
        label: "Campaigns",
        icon: "userProfile",
      },
      {
        href: "/pages/user-profile",
        name: "documents",
        label: "Documents",
        icon: "userProfile",
      },
      {
        href: "/pages/user-profile",
        name: "followers",
        label: "Followers",
        icon: "userProfile",
      },
    ],
  },
  {
    href: "/pages/account",
    name: "account-settings",
    label: "Account",
    icon: "account",
    hasSubRoutes: true,
    subRoutes: [
      { href: "/pages/account", name: "settings", label: "Settings", icon: "account" },
      { href: "/pages/account", name: "security", label: "Security", icon: "account" },
      { href: "/pages/account", name: "billing", label: "Billing", icon: "account" },
      { href: "/pages/account", name: "billing", label: "Billing", icon: "account" },
    ],
  },
  {
    href: "/pages/corporate",
    name: "corporate-settings",
    label: "Corporate",
    icon: "users",
    hasSubRoutes: true,
    subRoutes: [
      { href: "/pages/corporate", name: "teams", label: "Teams", icon: "users" },
      { href: "/pages/corporate", name: "policies", label: "Policies", icon: "users" },
      { href: "/pages/corporate", name: "partners", label: "Partners", icon: "users" },
      { href: "/pages/corporate", name: "partners", label: "Partners", icon: "users" },
    ],
  },
  {
    href: "/pages/blog",
    name: "blog-settings",
    label: "Blog",
    icon: "blog",
    hasSubRoutes: true,
    subRoutes: [
      { href: "/pages/blog", name: "articles", label: "Articles", icon: "blog" },
      { href: "/pages/blog", name: "tutorials", label: "Tutorials", icon: "blog" },
      { href: "/pages/blog", name: "news", label: "News", icon: "blog" },
    ],
  },
  {
    href: "/pages/social",
    name: "social-settings",
    label: "Social",
    icon: "social",
    hasSubRoutes: true,
    subRoutes: [
      { href: "/pages/social", name: "feed", label: "Feed", icon: "social" },
      { href: "/pages/social", name: "messages", label: "Messages", icon: "social" },
      { href: "/pages/social", name: "groups", label: "Groups", icon: "social" },
    ],
  },
];

export const users = [
  "Natali Craig",
  "Kate Morrison",
  "Drew Cano",
  "Orlando Diggs",
  "Andi Lane",
  "Koray Okumus",
  "Lana Steiner",
  "Carolyn Baldwin",
  "Devon Lane",
  "Courtney Henry",
  "Alex Johnson",
  "Sarah Williams",
  "Michael Brown",
  "Emily Davis",
  "James Wilson",
  "Olivia Martinez",
  "William Anderson",
  "Sophia Taylor",
  "Benjamin Thomas",
  "Isabella Jackson",
  "Lucas White",
  "Mia Harris",
  "Henry Martin",
  "Ava Thompson",
  "Alexander Garcia",
  "Charlotte Martinez",
  "Daniel Rodriguez",
  "Amelia Lewis",
  "Matthew Walker",
  "Harper Hall",
  "David Young",
  "Evelyn King",
  "Joseph Wright",
  "Abigail Lopez",
  "Andrew Hill",
  "Elizabeth Scott",
  "Joshua Green",
  "Sofia Adams",
  "Ryan Baker",
  "Avery Nelson",
  "Noah Carter",
  "Grace Mitchell",
  "Ethan Perez",
  "Chloe Roberts",
  "Logan Turner",
  "Victoria Phillips",
  "Nathan Campbell",
  "Lily Parker",
  "Caleb Evans",
  "Zoe Edwards",
];

export const projects = [
  "Landing Page",
  "CRM Admin pages",
  "Client Project",
  "Admin Dashboard",
  "App Landing Page",
  "UX Audit",
  "Product Website",
  "Marketing Emails",
  "Geo Portal",
  "Pitch Deck",
  "E-commerce Platform",
  "Mobile App",
  "API Integration",
  "Data Analytics",
  "Cloud Migration",
  "Security Audit",
  "Performance Optimization",
  "UI Redesign",
  "Backend Refactor",
  "Testing Suite",
  "Documentation Site",
  "Customer Portal",
  "Payment Gateway",
  "Inventory System",
  "Reporting Dashboard",
  "Notification Service",
  "Search Engine",
  "Content Management",
  "User Authentication",
  "Analytics Platform",
  "Social Media App",
  "Video Streaming",
  "Blog Platform",
  "E-learning System",
  "Task Management",
  "Calendar App",
  "Email Client",
  "File Storage",
  "Collaboration Tool",
  "Project Tracker",
  "HR Management",
  "Accounting Software",
  "CRM System",
  "Help Desk",
  "Survey Platform",
  "Event Management",
  "Booking System",
  "Delivery App",
  "Fitness Tracker",
  "Weather App",
];

export const addresses = [
  "Meadow Lane, Oakland",
  "Larry, San Francisco",
  "Bagwell Avenue, Ocala",
  "Washburn, Baton Rouge",
  "Nest Lane, Olivette",
  "Roosevelt Ave, Queens",
  "Westheimer Rd, Houston",
  "12th St, Austin",
  "Bright St, Denver",
  "Howard St, Chicago",
  "Main St, New York",
  "Park Ave, Los Angeles",
  "Broadway, Seattle",
  "Market St, Portland",
  "First Ave, Miami",
  "Second St, Boston",
  "Third Ave, Philadelphia",
  "Fourth St, Dallas",
  "Fifth Ave, Phoenix",
  "Sixth St, San Diego",
  "Seventh Ave, San Jose",
  "Eighth St, Austin",
  "Ninth Ave, Jacksonville",
  "Tenth St, Fort Worth",
  "Eleventh Ave, Columbus",
  "Twelfth St, Charlotte",
  "Thirteenth Ave, San Francisco",
  "Fourteenth St, Indianapolis",
  "Fifteenth Ave, Washington",
  "Sixteenth St, Nashville",
  "Seventeenth Ave, Boston",
  "Eighteenth St, Memphis",
  "Nineteenth Ave, Detroit",
  "Twentieth St, Oklahoma City",
  "Twenty-First Ave, Louisville",
  "Twenty-Second St, Baltimore",
  "Twenty-Third Ave, Milwaukee",
  "Twenty-Fourth St, Albuquerque",
  "Twenty-Fifth Ave, Tucson",
  "Twenty-Sixth St, Fresno",
  "Twenty-Seventh Ave, Sacramento",
  "Twenty-Eighth St, Kansas City",
  "Twenty-Ninth Ave, Mesa",
  "Thirtieth St, Atlanta",
  "Thirty-First Ave, Omaha",
  "Thirty-Second St, Raleigh",
  "Thirty-Third Ave, Miami",
  "Thirty-Fourth St, Cleveland",
  "Thirty-Fifth Ave, Tulsa",
  "Thirty-Sixth St, Oakland",
  "Thirty-Seventh Ave, Minneapolis",
  "Thirty-Eighth St, Wichita",
];

export const dates = [
  "Just now",
  "A minute ago",
  "2 minutes ago",
  "5 minutes ago",
  "10 minutes ago",
  "15 minutes ago",
  "30 minutes ago",
  "1 hour ago",
  "2 hours ago",
  "3 hours ago",
  "4 hours ago",
  "5 hours ago",
  "6 hours ago",
  "Today, 6:00 AM",
  "Today, 7:30 AM",
  "Today, 8:15 AM",
  "Today, 9:45 AM",
  "Today, 10:20 AM",
  "Today, 11:00 AM",
  "Today, 12:30 PM",
  "Today, 1:15 PM",
  "Today, 2:45 PM",
  "Today, 3:20 PM",
  "Today, 4:00 PM",
  "Today, 5:30 PM",
  "Yesterday",
  "Yesterday, 8:00 AM",
  "Yesterday, 2:00 PM",
  "Jan 15, 2024",
  "Jan 20, 2024",
  "Feb 2, 2024",
  "Feb 10, 2024",
  "Feb 18, 2024",
  "Mar 5, 2024",
  "Mar 10, 2024",
  "Mar 15, 2024",
  "Apr 1, 2024",
  "Apr 8, 2024",
  "Apr 18, 2024",
  "May 3, 2024",
  "May 12, 2024",
  "May 22, 2024",
  "Jun 5, 2024",
  "Jun 14, 2024",
  "Jun 25, 2024",
  "Jul 2, 2024",
  "Jul 11, 2024",
  "Jul 20, 2024",
  "Aug 1, 2024",
  "Aug 10, 2024",
];
